### ISSUE TITLE
Missing error information

### ISSUE THREAD

**Issue by fominok** [async-graphql/graphgate#8]
## Expected Behavior
Error when accessing service directly:
```
{
  "data": null,
  "errors": [
    {
      "message": "Some Server Error",
      "locations": [
        {
          "line": 4,
          "column": 7
        }
      ],
      "path": [
        "someMutation"
      ],
      "extensions": {
        "details": "sorry"
      }
    }
  ]
}
```
I expect this via Graphgate as well
## Actual Behavior
Same error via Graphgate:
```
{
  "data": null,
  "errors": [
    {
      "message": "Some Server Error"
    }
  ]
}
```

Am I misconfigured something?

**Comment by cawfeecoder** [comment]
@fominok Hey :) I know this ticket has been open for awhile and I had a similar need. I have a PR that modifies GraphGate to pass through the full error information of the upstream GraphQL service. You can find the PR here :) https://github.com/async-graphql/graphgate/pull/15
